---

# Charts release configuration file example
# This file is used to update the version of the helm charts and images in the values.yaml file
# It is used in the helm-charts-release action
# ${release} is replaced with the release version provided in the workflow

charts:
  - name: pgskipper-operator
    chart_file: charts/patroni-core/Chart.yaml
    values_file: charts/patroni-core/values.yaml
    image:
      - ghcr.io/netcracker/qubership-credential-manager:${release}
      - ghcr.io/netcracker/pgskipper-operator:${release}
      - ghcr.io/netcracker/pgskipper-patroni-16:${release}
      - ghcr.io/netcracker/pgskipper-operator-tests:${release}
